config/routes.rb
Rails.application.routes.draw do
  resources :brackets
  get 'brackets/new'

  get 'brackets/create'

  get 'tourney_sets/new'

  get 'tourney_sets/create'

  get 'players/new'

  get 'players/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :players
  resources :tourney_sets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bracket.rb
class Bracket < ApplicationRecord
  has_many :tourney_sets
  has_many :players, through: :pairings, source: :seedable, source_type: 'Player'
  has_many :pairings
  
end

app/models/pairing.rb
class Pairing < ApplicationRecord
  belongs_to :tourney_set
  belongs_to :seedable , polymorphic: true
  # TODO: Uncomment this when appropriate
  #belongs_to :bracket

end

app/models/player.rb
class Player < ApplicationRecord
  has_many :tourney_sets, inverse_of: 'game_player', through: :pairings
  has_many :brackets, through: :pairings, as: :seedable

end

app/models/tourney_set.rb
class TourneySet < ApplicationRecord
  has_many :pairings
  # TODO: This doesn't work
  # belongs_to :tourney_set, as: :seedable
  has_many :tourney_sets, as: :seedable
  belongs_to :bracket

  # TODO: This may be necessary later
  # belongs_to :winning_player, class_name: "Player"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brackets_controller.rb
class BracketsController < ApplicationController
  before_action :set_bracket, only: [:show, :edit, :update, :destroy]
  before_action :set_all_players, only: [:new, :edit]

  # GET /brackets
  # GET /brackets.json
  def index
    @brackets = Bracket.all
  end

  # GET /brackets/1
  # GET /brackets/1.json
  def show
  end

  # GET /brackets/new
  def new
    @bracket = Bracket.new
  end

  # GET /brackets/1/edit
  def edit
  end

  # POST /brackets
  # POST /brackets.json
  def create
    @bracket = Bracket.new(bracket_params)
    enrolled_players = []

    root_set = TourneySet.create
    next_set = TourneySet.create

    root_set.pairings << next_set

    @bracket.tourney_sets << root_set

    #for player_id in params["player_ids"]
    #  enrolled_players << Player.find(player_id)
    #end

    if @bracket.save
      redirect_to @bracket, notice: 'Bracket was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /brackets/1
  # PATCH/PUT /brackets/1.json
  def update
    respond_to do |format|
      if @bracket.update(bracket_params)
        format.html { redirect_to @bracket, notice: 'Bracket was successfully updated.' }
        format.json { render :show, status: :ok, location: @bracket }
      else
        format.html { render :edit }
        format.json { render json: @bracket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brackets/1
  # DELETE /brackets/1.json
  def destroy
    @bracket.destroy
    respond_to do |format|
      format.html { redirect_to brackets_url, notice: 'Bracket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bracket
      @bracket = Bracket.find(params[:id])
    end

    def set_all_players
      @all_players = Player.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bracket_params
      params.fetch(:bracket, {}).permit(:name)
    end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name)
    end
end

app/controllers/tourney_sets_controller.rb
class TourneySetsController < ApplicationController
  before_action :set_tourney_set, only: [:show, :edit, :update, :destroy]

  # GET /tourney_sets
  # GET /tourney_sets.json
  def index
    @tourney_sets = TourneySet.all
  end

  # GET /tourney_sets/1
  # GET /tourney_sets/1.json
  def show
  end

  # GET /tourney_sets/new
  def new
    @tourney_set = TourneySet.new
  end

  # GET /tourney_sets/1/edit
  def edit
  end

  # POST /tourney_sets
  # POST /tourney_sets.json
  def create
    @tourney_set = TourneySet.new(tourney_set_params)

    respond_to do |format|
      if @tourney_set.save
        format.html { redirect_to @tourney_set, notice: 'Tourney set was successfully created.' }
        format.json { render :show, status: :created, location: @tourney_set }
      else
        format.html { render :new }
        format.json { render json: @tourney_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tourney_sets/1
  # PATCH/PUT /tourney_sets/1.json
  def update
    respond_to do |format|
      if @tourney_set.update(tourney_set_params)
        format.html { redirect_to @tourney_set, notice: 'Tourney set was successfully updated.' }
        format.json { render :show, status: :ok, location: @tourney_set }
      else
        format.html { render :edit }
        format.json { render json: @tourney_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tourney_sets/1
  # DELETE /tourney_sets/1.json
  def destroy
    @tourney_set.destroy
    respond_to do |format|
      format.html { redirect_to tourney_sets_url, notice: 'Tourney set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tourney_set
      @tourney_set = TourneySet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tourney_set_params
      params.fetch(:tourney_set, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brackets_helper.rb
module BracketsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/tourney_sets_helper.rb
module TourneySetsHelper
end

app/views/brackets/_form.html.erb
<%= simple_form_for @bracket do |f| %>
<%= f.input :name %>
<%# select_tag 'player_ids',
    options_from_collection_for_select(@all_players, :id, :name),
    multiple: true, class: 'multiselectuser' %>
<%= f.button :submit %>
<% end %>

app/views/brackets/edit.html.erb
<h1>Editing Bracket</h1>

<%= render 'form' %>

<%= link_to 'Show', @bracket %> |
<%= link_to 'Back', brackets_path %>

app/views/brackets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brackets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brackets.each do |bracket| %>
      <tr>
        <td><%= link_to bracket.name, bracket %></td>
        <td><%= link_to 'Edit', edit_bracket_path(bracket) %></td>
        <td><%= link_to 'Destroy', bracket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bracket', new_bracket_path %>

app/views/brackets/new.html.erb
<h1>New Bracket</h1>

<%= render 'form' %>

<%= link_to 'Back', brackets_path %>

app/views/brackets/show.html.erb
<p id="notice"><%= notice %></p>
<%= @bracket.name %>
<%= link_to 'Edit', edit_bracket_path(@bracket) %> |
<%= link_to 'Back', brackets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TourneyFriend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= simple_form_for(@player) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= simple_form_for @player do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

<% @player.errors.each do |attr, msg| %>
<%= "#{attr} #{msg}" %>
<% end %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/tourney_sets/_form.html.erb
<%= simple_form_for(@tourney_set) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tourney_sets/edit.html.erb
<h1>Editing Tourney Set</h1>

<%= render 'form', tourney_set: @tourney_set %>

<%= link_to 'Show', @tourney_set %> |
<%= link_to 'Back', tourney_sets_path %>

app/views/tourney_sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tourney Sets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tourney_sets.each do |tourney_set| %>
      <tr>
        <td><%= link_to 'Show', tourney_set %></td>
        <td><%= link_to 'Edit', edit_tourney_set_path(tourney_set) %></td>
        <td><%= link_to 'Destroy', tourney_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tourney Set', new_tourney_set_path %>

app/views/tourney_sets/new.html.erb
<h1>New Tourney Set</h1>

<%= render 'form', tourney_set: @tourney_set %>

<%= link_to 'Back', tourney_sets_path %>

app/views/tourney_sets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tourney_set_path(@tourney_set) %> |
<%= link_to 'Back', tourney_sets_path %>